---
title: CV
format:
  quarto-cv-pdf:
    keep_tex: true
mainfont: FandolSong
author: 应可钧 博士
date: last-modified
address: "290 Jane Stanford Way, Stanford, CA 94305"
email: keying@stanford.edu | kying0@uw.edu
fontsize: 11pt
fontcolor: darktext
backgroundcolor: darkbackground
urlcolor: mycolor
github: albert-ying
orcid: 0000-0002-1791-6176
web: kejunying.com
fontawesome: yes
nocite: '@*'
validate-yaml: false
csl: apa-cv.csl
---

# 教育经历与专业培训
\hrule

**斯坦福大学 & 华盛顿大学** \hfill Stanford, CA & Seattle, WA  
*博士后研究员，Tony Wyss-Coray实验室 & David Baker实验室（联合指导）* \hfill 2025年6月至今

\vspace{-0.5\baselineskip}
- 由Wyss-Coray博士和Baker博士联合指导，获NIH/NIA F99/K00奖学金资助
- 结合衰老生物学与蛋白质从头设计，应对神经退行性疾病
- 专注于从头设计解聚酶以对抗神经元中的蛋白质聚集
- 构建先进的衰老时钟和蛋白质组数据基础模型

**哈佛大学** \hfill Cambridge, MA  
*Ph.D.，公共卫生生物科学* \hfill 2019年7月 -- 2025年5月

\vspace{-0.5\baselineskip}
- 论文："衰老的量化"
- 导师：Vadim Gladyshev博士，哈佛医学院，布莱根妇女医院
- 论文指导委员会：Brendan Manning博士、David Sinclair博士、Shamil Sunyaev博士
- 研究方向：通过多组学建模和因果推断理解衰老的机制
- 构建了**首个因果增强型衰老时钟** / **目前最大的生物年龄数据库和智能体系统（ClockBase Agent，200万+样本，4万+分析）** / **首个DNA甲基化组基础模型（MethylGPT）**

**哈佛大学** \hfill Cambridge, MA  
*M.S.，计算科学工程* \hfill 2023年7月 -- 2024年5月

\vspace{-0.5\baselineskip}
- 博士学习期间的第二专业

**加州大学伯克利分校** \hfill Berkeley, CA  
*访问学生，综合生物学* \hfill 2017年8月 -- 2017年12月

**中山大学** \hfill 广州，中国  
*B.S.，生命科学* \hfill 2015年9月 -- 2019年6月

\vspace{-0.5\baselineskip}
- 论文：基于活细胞中分子荧光互补系统筛选hTERC相互作用组
- 逸仙荣誉学院项目（前0.5%）
- 高考成绩（前0.6%）


# 研究经历
\hrule

**斯坦福大学 & 华盛顿大学** \hfill Stanford, CA & Seattle, WA  
**衰老的蛋白质设计** *博士后研究员，Wyss-Coray实验室 & Baker实验室* \hfill 2025年6月至今  
*访问学者，Wyss-Coray实验室 & Baker实验室* \hfill 2024年11月 -- 2025年5月

**Avinasi Labs** \hfill San Francisco, CA  
**去中心化长寿数据收集** *联合创始人* \hfill 2025年1月至今

**哈佛医学院，布莱根妇女医院** \hfill Boston, MA  
**生物衰老** *研究生研究员，Vadim Gladyshev实验室* \hfill 2020年3月 -- 2025年5月

**哈佛医学院，波士顿儿童医院** \hfill Boston, MA  
**RNA修饰** *研究生研究员（轮转），Eric Greer实验室* \hfill 2020年1月 -- 2020年3月

**哈佛医学院** \hfill Boston, MA  
**细胞重编程** *研究生研究员（轮转），David Sinclair实验室* \hfill 2019年10月 -- 2019年12月

**哈佛大学陈曾熙公共卫生学院** \hfill Boston, MA  
**mTORC1** *研究生研究员（轮转），Brendan Manning实验室* \hfill 2019年7月 -- 2019年10月

**本科研究经历** \hfill 2015年 -- 2019年

- **中山大学**，*端粒与端粒酶* \hfill 松阳洲实验室
- **爱丁堡大学**，*群体遗传学* \hfill Xia Shen实验室
- **华盛顿大学**，*阿卡波糖与雷帕霉素* \hfill Matt Kaeberlein实验室
- **巴克老龄化研究所**，*衰老细胞清除剂* \hfill Judith Campisi实验室
- **加州大学伯克利分校**，*SIRT7* \hfill Danica Chen实验室
- **中山大学**，*端粒与DNA甲基化* \hfill 容益康实验室

# 基金资助
\hrule

**K00博士后过渡奖** \hfill NIH/NIA
*利用因果衰老生物标志物和蛋白质设计开发新型抗衰老干预措施*， \hfill 2025年 -- 2028年

**F99向衰老研究过渡博士生奖** \hfill NIH/NIA
*利用因果衰老生物标志物和蛋白质设计开发新型抗衰老干预措施*， \hfill 2024年 -- 2025年

- 奖项文件编号：FAG088431A（负责人）
- 获得**满分10分**的影响评分

# 发表论文
\hrule

^†^ 通讯作者；^\*^ 共同第一作者；^+^ 以联盟作者身份贡献

## 精选论文与预印本

\textbf{\underline{Ying, K.}}，Paulson, S.，Eames, A.，Tyshkovskiy, A.，...，Gladyshev, V. N. (2025). *A Unified Framework for Systematic Curation and Evaluation of Aging Biomarkers*。**Nat. Aging**. <https://www.nature.com/articles/s43587-025-00987-y>

Moqri, M.^\*^，\textbf{\underline{Ying, K.$^{*}$}}，Poganik, J.^\*^，Herzog, C.^\*^，Chen, Q.，Emamifar, M.，...，Gladyshev, V. N. (2025). Integrative epigenetics and transcriptomics identify aging genes in human blood。**Nat. Commun.（已接受）**. <https://doi.org/10.1101/2024.05.30.596713>

Wu, X.^\*^，Liu, H.^\*^，\textbf{\underline{Ying, K.$^{*\dagger}$}} (2025). Biological Age, Aging Clocks, and the Interplay with Lymphoid Neoplasms: Mechanisms and Clinical Frontiers。**Lymphatics**，*3*(3)，19. <https://doi.org/10.3390/lymphatics3030019>

\textbf{\underline{Ying, K.$^{\dagger}$}} (2024). Causal inference for epigenetic ageing。**Nat. Rev. Genet.**，1--1. <https://doi.org/10.1038/s41576-024-00799-7>

\textbf{\underline{Ying, K.}}，Castro, J. P.，Shindyapina, A. V.，...，Gladyshev, V. N. (2024). Depletion of loss-of-function germline mutations in centenarians reveals longevity genes。**Nat. Commun.**，*15*(1)，5956. <https://doi.org/10.1038/s41467-024-50098-2>

\textbf{\underline{Ying, K.}}，Liu, H.，Tarkhov, A. E.，...，Gladyshev, V. N. (2024). Causality-enriched epigenetic age uncouples damage and adaptation。**Nat. Aging（2月封面）**，1--16. <https://doi.org/10.1038/s43587-023-00557-0> 

\textbf{\underline{Ying, K.}}，Zhai, R.，Pyrkov, T. V.，...，Gladyshev, V. N. (2021). Genetic and phenotypic analysis of the causal relationship between aging and COVID-19。**Commun. Med.**，*1*(1)，35. <https://doi.org/10.1038/s43856-021-00033-z> 

\textbf{\underline{Ying, K.$^{*\dagger}$}}，Tyshkovskiy, A.，Moldakozhayev, A.，...，Gladyshev, V. N. (2025). Massive AI agent mining of aging interventions from millions of molecular profiles。**bioRxiv（更新版本，Nature投稿中）**. <https://doi.org/10.1101/2023.02.28.530532> 

\textbf{\underline{Ying, K.$^{\dagger}$}}，Song, J.，Cui, H.，...，Gladyshev, V. N$^{\dagger}$. (2024). MethylGPT: a foundation model for the DNA methylome。**bioRxiv（Nature Machine Intelligence投稿中）**. <https://doi.org/10.1101/2024.10.30.621013>

\textbf{\underline{Ying, K.}}，Paulson, S.，Reinhard, J.，...，Gladyshev, V. N. (2024). An Open Competition for Biomarkers of Aging。**bioRxiv**. <https://doi.org/10.1101/2024.10.29.620782>

\textbf{\underline{Ying, K.}}，Tyshkovskiy, A.，Chen, Q.，...，Gladyshev, V. N. (2024). High-dimensional Ageome Representations of Biological Aging across Functional Modules。**bioRxiv（Nature Aging二次修订中）**. <https://doi.org/10.1101/2024.09.21.570935>

\textbf{\underline{Ying, K.}}，Tyshkovskiy, A.，Trapp, A.，...，Gladyshev, V. N. (2023). ClockBase: A comprehensive platform for biological age profiling in human and mouse。**bioRxiv**. <https://doi.org/10.1101/2023.02.28.530532> 

## 其他论文

Zhang, O.，Lin, H.，Zhang, X.，Wang, X.，Wu, Z.，Ye, Q.，Zhao, W.，Wang, J.，\textbf{\underline{Ying, K.}}，Kang, Y.，Hsieh, C.-Y.，Hou, T. (2025). Graph neural networks in modern AI-aided drug discovery。**Chem. Rev.**，125，10001--10103. <https://doi.org/10.1021/acs.chemrev.5b00254>

Zhang, O.，...，\textbf{\underline{Ying, K.}}，Huang, Y.，Zhao, H.，Kang, Y.，Pan, P.，Wang, J.，Guo, D.，Zheng, S.，Hsieh, C.-Y.，& Hou, T. (2025). ECloudGen: leveraging electron clouds as a latent variable to scale up structure-based molecular design。**Nat. Comput. Sci.**. <https://doi.org/10.1038/s43588-025-00886-7>

Farinas, A.，Rutledge, J.，Bot, V. A.，Western, D.，\textbf{\underline{Ying, K.}}，Lawrence, K. A.，Oh, H. S. H.，...，Wyss-Coray, T. (2025). Disruption of the cerebrospinal fluid–plasma protein balance in cognitive impairment and aging。**Nat. Med.**，1--12. <https://doi.org/10.1038/s41591-025-03831-3>

Rothi, M.H.，Sarkar, G.C.，Haddad, J.A.，Mitchell, W.，\textbf{\underline{Ying, K.}}，等 (2025). The 18S rRNA methyltransferase DIMT-1 regulates lifespan in the germline later in life。**Nat. Commun.**，16，6944. <https://doi.org/10.1038/s41467-025-62323-7>

Grzeczka, A.，Iqbal, S.，\textbf{\underline{Ying, K.}}，Kordowitzki, P. (2025). Circular RNAs as regulators and biomarkers of mammalian ovarian ageing。**GeroScience**，1--19. <https://doi.org/10.1007/s11357-025-01798-0>

Jacques, E.，Herzog, C.，\textbf{\underline{Ying, K.}}，...，Gladyshev, V. N. (2025). Invigorating discovery and clinical translation of aging biomarkers。**Nat. Aging**，1--5.

Goeminne, L. J. E.，Vladimirova, A.，Eames, A.，Tyshkovskiy, A.，Argentieri, M. A.，\textbf{\underline{Ying, K.}}，Moqri, M.，& Gladyshev, V. N. (2025). Plasma protein-based organ-specific aging and mortality models unveil diseases as accelerated aging of organismal systems。**Cell Metab.**，<https://doi.org/10.1016/j.cmet.2024.03.007>

Gladyshev, V. N.，Anderson, B.，Barlit, H.，...，\textbf{\underline{Ying, K.}}，Yunes, J.，Zhang, B.，& Zhavoronkov, A. (2024). Disagreement on foundational principles of biological aging。**PNAS Nexus**，*3*(12)，pgae499. <https://doi.org/10.1093/pnasnexus/pgae499>

Lyu, YX.^\*^，Fu, Q.^\*^，Wilczok, D.^\*^，\textbf{\underline{应可钧$^{*}$}}，King, A.，...，Bakula, D. (2024). Longevity biotechnology: Bridging AI, biomarkers, geroscience and clinical applications for healthy longevity。**Aging**，*16*(1)，1--25. <https://doi.org/10.18632/aging.205397>

\textbf{\underline{衰老生物标志物联盟$^{+}$}}，Herzog, C. M. S.，Goeminne, L. J. E.，Poganik, J. R.，...，Gladyshev, V. N. (2024). Challenges and recommendations for the translation of biomarkers of aging。**Nat. Aging**，1--12. <https://doi.org/10.1038/s43587-024-00683-3>

Castro, J. P.，Shindyapina, A. V.，Barbieri, A.，\textbf{\underline{Ying, K.}}，...，Gladyshev, V. N. (2024). Age-associated clonal B cells drive B cell lymphoma in mice。**Nat. Aging**，*4*(8)，1--15. <https://doi.org/10.1038/s43587-024-00671-7>

Moqri, M.，...，de Sena Brandine, G.，\textbf{\underline{Ying, K.}}，Tarkhov, A.，...，Sebastiano, V. (2024). PRC2-AgeIndex as a universal biomarker of aging and rejuvenation。**Nat. Commun.**，*15*(1)，5956. <https://doi.org/10.1038/s41467-024-50098-2>

Tarkhov, A. E.，Lindstrom-Vautrin, T.，Zhang, S.，\textbf{\underline{Ying, K.}}，Moqri, M.，...，Gladyshev, V. N. (2024). Nature of epigenetic aging from a single-cell perspective。**Nat. Aging**，1--17. <https://doi.org/10.1038/s43587-023-00555-2> 

Moqri, M.，Herzog, C.，Poganik, J. R.，\textbf{\underline{Ying, K.}}，...，Ferrucci, L. (2024). Validation of biomarkers of aging。**Nat. Med.**，1--13. <https://doi.org/10.1038/s41591-023-02784-9> 

Griffin, P. T.，...，Kerepesi, C.，\textbf{\underline{Ying, K.}}，...，Sinclair, D. A. (2024). TIME-seq reduces time and cost of DNA methylation measurement for epigenetic clock construction。**Nat. Aging**，1--14. <https://doi.org/10.1038/s43587-023-00555-2> 

Moqri, M.，Herzog, C.，Poganik, J. R.，\textbf{\underline{衰老生物标志物联盟$^{+}$}}，...，Gladyshev, V. N. (2023). Biomarkers of aging for the identification and evaluation of longevity interventions。**Cell**，*186*(18)，3758--3775. <https://doi.org/10.1016/j.cell.2023.08.003>

Liberman, N.，Rothi, M. H.，Gerashchenko, M. V.，Zorbas, C.，Boulias, K.，MacWhinnie, F. G.，\textbf{\underline{Ying, K.}}，Flood Taylor, A.，...，Greer, E. L. (2023). 18S rRNA methyltransferases DIMT1 and BUD23 drive intergenerational hormesis。**Mol. Cell**，*83*(18)，3268--3282.e7. <https://doi.org/10.1016/j.molcel.2023.08.014> 

Bitto, A.，Grillo, A. S.，Ito, T. K.，Stanaway, I. B.，Nguyen, B. M. G.，\textbf{\underline{Ying, K.}}，...，Kaeberlein, M. (2023). Acarbose suppresses symptoms of mitochondrial disease in a mouse model of Leigh syndrome。**Nat. Metab.**，*5*(6)，955--967. <https://doi.org/10.1038/s42255-023-00815-w> 

Emmrich, S.，Trapp, A.，Tolibzoda Zakusilo, F.，Straight, M. E.，\textbf{\underline{Ying, K.}}，Tyshkovskiy, A.，...，Gorbunova, V. (2022). Characterization of naked mole-rat hematopoiesis reveals unique stem and progenitor cell patterns and neotenic traits。**EMBO J.**，*41*(15)，e109694. <https://doi.org/10.15252/embj.2021109694> 

Yang, Z.，...，Guo, H.，\textbf{\underline{Ying, K.}}，Gustafsson, S.，...，Shen, X. (2022). Genetic Landscape of the ACE2 Coronavirus Receptor。**Circulation**，*145*(18)，1398--1411. <https://doi.org/10.1161/CIRCULATIONAHA.121.057888> 

Li, T.，Ning, Z.，Yang, Z.，Zhai, R.，Zheng, C.，Xu, W.，Wang, Y.，\textbf{\underline{Ying, K.}}，Chen, Y.，& Shen, X. (2021). Total genetic contribution assessment across the human genome。**Nat. Commun.**，*12*(1)，2845. <https://doi.org/10.1038/s41467-021-23124-w> 

Zhu, J.，Xu, M.，Liu, Y.，Zhuang, L.，\textbf{\underline{Ying, K.}}，Liu, F.，...，Songyang, Z. (2019). Phosphorylation of PLIN3 by AMPK promotes dispersion of lipid droplets during starvation。**Protein Cell**，*10*(5)，382--387. <https://doi.org/10.1007/s13238-018-0593-9>


## 其他预印本

Zhang, O.，Zhang, X.，Lin, H.，Tan, C.，Wang, Q.，Mo, Y.，...，\textbf{\underline{Ying, K.}}，Li, J.，Zeng, Y.，Lang, L.，Pan, P.，Cao, H.，Song, Z.，Qiang, B.，Wang, J.，Ji, P.，Bai, L.，Zhang, J.，Hsieh, C.-Y.，Heng, P. A.，Sun, S.，Hou, T.，& Zheng, S. (2025). ODesign: A World Model for Biomolecular Interaction Design。**arXiv**. <https://odesign1.github.io/>

Mavrommatis, C.，Belsky, D.，\textbf{\underline{Ying, K.}}，Moqri, M.，Campbell, A.，Richmond, A.，...，Gladyshev, V. N. (2025). *An unbiased comparison of 14 epigenetic clocks in relation to 10-year onset of 174 disease outcomes in 18,859 individuals*。**medRxiv**. <https://doi.org/10.1101/2025.07.14.25331494>

Galkin, F.，...，Tyshkovskiy, A.，\textbf{\underline{Ying, K.}}，Gladyshev, V. N.，& Zhavoronkov, A. (2024). Precious3GPT: Multimodal Multi-Species Multi-Omics Multi-Tissue Transformer for Aging Research and Drug Discovery。**bioRxiv**. <https://doi.org/10.1101/2024.07.25.605062>

Tyshkovskiy, A.，Kholdina, D.，\textbf{\underline{Ying, K.}}，Davitadze, M.，...，Gladyshev, V. N. (2024). Transcriptomic Hallmarks of Mortality Reveal Universal and Specific Mechanisms of Aging, Chronic Disease, and Rejuvenation。**bioRxiv**. <https://doi.org/10.1101/2024.07.04.601982>

Moqri, M.，Poganik, J. R.，Herzog, C.，\textbf{\underline{Ying, K.}}，Chen, Q.，...，Gladyshev, V. N. (2024). Integrative epigenetics and transcriptomics identify aging genes in human blood。**bioRxiv**. <https://doi.org/10.1101/2024.05.30.596713>

Rothi, M. H.，Sarkar, G. C.，Al Haddad, J.，Mitchell, W.，\textbf{\underline{Ying, K.}}，Pohl, N.，...，Greer, E. L. (2024). The 18S rRNA Methyltransferase DIMT-1 Regulates Lifespan in the Germline Later in Life。**bioRxiv**. <https://doi.org/10.1101/2024.05.15.570935>

Zhang, B.，Tarkhov, A. E.，Ratzan, W.，\textbf{\underline{Ying, K.}}，Moqri, M.，...，Gladyshev, V. N. (2022). *Epigenetic profiling and incidence of disrupted development point to gastrulation as aging ground zero in Xenopus laevis*。**bioRxiv**. <https://doi.org/10.1101/2022.08.02.502559>

# 专利
\hrule

V. N. Gladyshev，**K. Ying**，"High-dimensional measurement of biological age" (2024)。*临时专利申请*

V. N. Gladyshev，**K. Ying**，"Mapping CpG sites to quantify aging traits" (2024)。*WO2024039905A2*

# 软件与数据库
\hrule

**MethylGPT** (2024) \hfill <https://github.com/MethylGPT/MethylGPT>

**Biolearn** (2024) \hfill <https://bio-learn.github.io/>

**ClockBase** (2023) \hfill <https://www.clockbase.org/>


# 演讲报告
\hrule

## 口头报告

**衰老生物标志物研讨会2025** \hfill Boston, MA  
_利用AI智能体从数百万分子谱中大规模挖掘衰老调节干预措施_ \hfill 2025年

**美国人类遗传学学会2025年年会** \hfill Boston, MA  
_解码衰老甲基化组：从因果推断到基础模型_ \hfill 2025年

**第6届TimePie长寿论坛** \hfill 上海，中国  
_利用AI智能体从数百万分子谱中大规模挖掘衰老调节干预措施_ \hfill 2025年

**CSH亚洲会议：干细胞、衰老与再生** \hfill 苏州，中国  
_利用AI智能体从数百万分子谱中大规模挖掘衰老调节干预措施_ \hfill 2025年

**Keystone研讨会：衰老的新前沿——再生与老年治疗** \hfill Breckenridge, CO  
_MethylGPT：DNA甲基化组的基础模型_ \hfill 2025年

**衰老生物标志物研讨会** \hfill Boston, MA  
_衰老生物标志物的标准化与BoA挑战_ \hfill 2024年

**哈佛大学GRIP演讲** \hfill Boston, MA  
_因果衰老生物标志物赋能无偏抗衰老治疗筛选_ \hfill 2024年

**第4届TimePie长寿论坛** \hfill 上海，中国  
_因果衰老生物标志物作为无偏抗衰老治疗筛选工具_ \hfill 2023年

**全球美容与抗衰老大会（GCAA2023）** \hfill 新加坡  
_因果衰老生物标志物作为无偏抗衰老治疗筛选工具_ \hfill 2023年

**第10届衰老研究与药物发现会议（ARDD2023）** \hfill Copenhagen, Denmark  
_因果表观遗传年龄解耦损伤与适应_ \hfill 2023年

**AGE 2023第51届年会** \hfill Oklahoma City, OK  
_因果表观遗传年龄解耦损伤与适应_ \hfill 2023年

**博德研究所MPG研讨会** \hfill Cambridge, MA  
_因果表观遗传年龄解耦损伤与适应_ \hfill 2023年

**哈佛大学GRIP演讲** \hfill Boston, MA  
_因果表观遗传年龄解耦损伤与适应_ \hfill 2022年

**Targeting Metabesity 2022**，"荣誉提名" \hfill 线上会议  
_因果表观遗传年龄解耦损伤与适应_ \hfill 2022年

**GSA 2021年度科学会议** \hfill 线上会议  
_衰老与COVID-19之间因果关系的遗传学和表型证据_ \hfill 2021年

## 受邀报告

**圣犹大儿童研究医院**，Zhaoming Wang博士主持 \hfill Memphis, TN  
_MethylGPT与因果增强型表观遗传时钟_ \hfill 2025年

**长寿倡议联盟科学家聚焦**， \hfill 线上播客  
_第14集：Albert Ying_ \hfill 2024年

**BioAge研讨会**，Robert Hughes博士和Paul Timmers博士主持 \hfill Boston, MA  
_Ageome：更高维度的生物年龄_ \hfill 2024年

**MRC综合流行病学单位研讨会** \hfill Bristol, UK  
_表观遗传时钟与孟德尔随机化_ \hfill 2024年

**NIA EL项目联合会议**，国家老龄化研究所 \hfill 线上网络研讨会  
_衰老时钟_ \hfill 2024年

**衰老生物标志物挑战赛**，Foresight Institute \hfill 线上网络研讨会  
_与Foresight的更新网络研讨会_ \hfill 2024年

**Everything Epigenetics**，Hannah Went主持的播客 \hfill 线上播客  
_因果表观遗传年龄解耦损伤与适应_ \hfill 2024年

**香港中文大学**，王鑫博士主持 \hfill 香港，中国  
_因果衰老生物标志物作为系统性抗衰老治疗筛选工具_ \hfill 2024年

**香港中文大学**，王鑫博士主持 \hfill 香港，中国  
_因果衰老生物标志物作为系统性抗衰老治疗筛选工具_ \hfill 2023年

**北京大学**，韩敬东博士主持 \hfill 北京，中国  
_因果衰老生物标志物与ClockBase_ \hfill 2023年

**中国科学院**，周旭明博士主持 \hfill 北京，中国  
_因果表观遗传年龄解耦损伤与适应_ \hfill 2022年

**Foresight Institute**，Allison Duettmann主持 \hfill 线上研讨会  
_遗传变异、衰老与COVID-19的关系 | Joris Deelen、Albert Ying_ \hfill 2020年

# 荣誉与奖项
\hrule

**半决赛入围者**，哈佛校长创新挑战赛，医疗保健与生命科学赛道 \hfill 2025年

**最佳海报奖**，首届衰老生物标志物研讨会 \hfill 2023年

**最佳海报奖**，戈登研究会议，系统衰老 \hfill 2022年

**黑客马拉松获胜者**，长寿黑客马拉松，VitaDAO \hfill 2021年

**逸仙荣誉学院项目**，中山大学 \hfill 2016年 -- 2019年

**逸仙奖学金**，中山大学 \hfill 2016年 -- 2019年

# 专业经验
\hrule

## 服务与领导

**理事会成员**，救生艇基金会 \hfill 2025年至今

**成员**，Norn长寿联盟 \hfill 2025年至今

**评委与导师**，智能体AI对抗衰老黑客马拉松 \hfill 2025年

**核心成员**，衰老生物标志物联盟 \hfill 2024年至今

**组织者**，衰老生物标志物挑战赛 \hfill 2024年至今

**主席**，哈佛疾病与健康跨学科讨论组 \hfill 2024年 -- 2025年

**议程贡献者**，世界经济论坛 \hfill 2024年

**组委会成员**，衰老生物标志物研讨会2024 \hfill 2024年

**组委会成员**，衰老生物标志物研讨会2023 \hfill 2023年

## 教学与指导

**导师**，元培青年学者项目 \hfill 2023年 -- 2024年

**讲师**，哈佛公共卫生青年一代研讨会 \hfill 2023年

## 指导学生

**博士前学生**：Ali Doga Yucel、李思远、刘涵娜、李东贤、张艺坤

## 审稿期刊

*Nat. Aging*、*Nat. Commun.*、*Commun. Med.*、*Genome Med.*、*BMC Nephrol.*、*Lipids Health Dis.*、*Clin. Proteomics*、*Evid. Based Complement. Alternat. Med.*、*Sci. Rep.*

# 推荐人
\hrule

**Dr. Tony Wyss-Coray**，博士后联合导师 \hfill twc\@stanford.edu  
D.H. Chen杰出神经学与神经科学教授，斯坦福大学

**Dr. David Baker**，博士后联合导师 \hfill dbaker\@uw.edu  
生物化学教授，华盛顿大学

**Dr. Vadim Gladyshev**，博士导师 \hfill vgladyshev\@bwh.harvard.edu  
医学教授，哈佛医学院

**Dr. Steve Horvath**，合作者 \hfill shorvath\@mednet.ucla.edu  
人类遗传学教授，加州大学洛杉矶分校

**Dr. David Sinclair**，论文指导委员会 \hfill david_sinclair\@hms.harvard.edu  
遗传学教授，哈佛医学院

**Dr. Matt Kaeberlein**，导师 \hfill kaeber\@uw.edu  
病理学教授，华盛顿大学
